### PR TITLE
Setup sparklines with go-bindata

### PR DESCRIPTION
**Pull request by cultureulterior**
- Uses previous websocket pull request
- Uses(gets, and uses) go-bindata, as discussed with Jonas

Html infrastructure:
- Uses jquery, jquery-sparkline, Reconnecting-websocket

### CODE REVIEW

**Comment by zimbatm** [comment]
The makefile is missing `.PHONY: default build`. You could also add a `go fmt ./...` directive in the build to avoid these tab-vs-space issues.

**Comment by cultureulterior** [comment]
@mloughran Alert

**Comment by mloughran** [comment]
I don't think we should include the viewer application inside stagger. It would be good to be able to iterate it rapidly, which is made much harder if if requires re-packaging and restarting stagger (which should be long running). Even when the viewer is stable I am still inclined to keep stagger as small as simple as possible.

**Comment by mloughran** [comment]
Presumably we can just have the viewer online somewhere and point it to the stagger websocket endpoint?

**Comment by cultureulterior** [comment]
- I don't see sparklines being iterated that much locally, since they are just for simple viewing of stats, essentially a improved stail
- It really doesn't matter if stagger is restarted right now, since it has no history
- I don't like having the viewer separate- it'll be so nice when we can just go to any machine and look at the sparkline by going to say edge80:8999 and seeing the sparklines for that machine

**Comment by cultureulterior** [comment]
@zimbatm I'm in favor of the format directive, but you already made a pull request for that

**Comment by cultureulterior** [comment]
Also, if the viewer application is embedded, it knows the address of the websocket automatically, @mloughran

**Comment by cultureulterior** [comment]
Also @mloughran all my recent commits together only make for a 5% increase in the binary size

**Comment by cultureulterior** [comment]
Reviewed by zimbatm.

**Pull request merged**
